// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJiKebE45hLk7CDLmTmxds85lw6bpMg3I',
    appId: '1:749700258511:web:cdea08784980cbdbb135ba',
    messagingSenderId: '749700258511',
    projectId: 'safetyapp-420011',
    authDomain: 'safetyapp-420011.firebaseapp.com',
    storageBucket: 'safetyapp-420011.appspot.com',
    measurementId: 'G-XSDP1PXNQ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOJ1dqD3j7LUwQ__7DXjQtuNkigl34f0g',
    appId: '1:749700258511:android:42ce2fd7cd56a3d1b135ba',
    messagingSenderId: '749700258511',
    projectId: 'safetyapp-420011',
    storageBucket: 'safetyapp-420011.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWuPHlWf-v8P6tUGp1vgdVUk9a0OJ3aVE',
    appId: '1:749700258511:ios:6732257a8fcac7c4b135ba',
    messagingSenderId: '749700258511',
    projectId: 'safetyapp-420011',
    storageBucket: 'safetyapp-420011.appspot.com',
    iosBundleId: 'com.example.flutterApplication4',
  );
}
